### ISSUE TITLE
Travel Icon

### ISSUE THREAD

**Issue by Uchman21** [HexTree/orientation-app#47]
I still prefer the bus icon since the bus can represent both long travels or just the in-camp bus schedule which we have in that menu. Having the camel and palm kinda makes it look like a menu more of only for vacations.

**Comment by HexTree** [comment]
I originally wanted the palm tree icon because the Travel section was going to be mostly about tourism stuff. But since we have been asked to remove all touristy stuff, and also since we've added the bus routing section, I guess the bus icon is now more appropriate. Ok, let's revert to the bus icon, and we can save the palm tree icon for the future if and when we make a new smartphone app with all the travel stuff.

**Comment by Uchman21** [comment]
I would like to request something like a map icon too.

**Comment by hadjimy** [comment]
What kind of map icon you would like? Where's going to be used?

**Comment by Uchman21** [comment]
Just a simple map icon. Maybe something with a map pin. To be used on the map button

**Comment by HexTree** [comment]
Do you have a new layout in mind? I don't see how a map icon can be introduced to the present layout.

**Comment by hadjimy** [comment]
I can make a map of the region to be used as a button image.

**Comment by Uchman21** [comment]
oh the current buttons under travel which are currently blank. not necessary to be a map of a region but just an icon indicating its a map button. For the bus planner button, i will use the bus icon

**Comment by hadjimy** [comment]
Don't know if the resolution of the bus icon is enough. That button takes full width of the screen. But if it looks good then go for it.

**Comment by HexTree** [comment]
I don't know about putting icons on buttons themselves, especially with the text present. It sounds a bit strange.

**Comment by Uchman21** [comment]
Or rather don't worry.. i used a plane color for the button. Yeah you are correct , with the text, it looks strange
