### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Uchman21** [HexTree/orientation-app#48]
Please to make all the icons and pictures compatible for all devices, i need a list of all the new added icons and pictures ASAP.

**Comment by hadjimy** [comment]
All main menu icons are updated and are compatible on different devices.
Contact icons are in orientation-app/android/orientation_app/app/src/main/res/drawable/contacts/
and that's the maximum resolution available.

The following are to be used in the contacts menu:
community_info.png
goverment_affairs.png
helpdesk.png
i-hub.png
it.png
mail.png
maintenance.png
medical.png
security.png
taxi.png

**Comment by HexTree** [comment]
For the residential life icon, I can't not make any sense of what is in that photo. Maybe we can just have an icon with a house?

For medical maybe we should use the standard International red cross, since it's a universal symbol for healthcare. It will be more familiar to new arrivals. I've not seen the red crescent before, is that what KMC use?

For emergency perhaps we should have a general purpose emergency icon, not specific to security. Students need to know they can call it for anything; medical, fire, etc., not only Security.

**Comment by HexTree** [comment]
Ah, I've read more about the red crescent. I didn't realise it is in widespread use. Okay let's keep it.

**Comment by hadjimy** [comment]
You should not need to use the residential icon, it's low resolution and it's not in the list of phones I sent.
The red crescent is the icon used for medical purposes in Muslim countries. I will add an alternative icon though. Don't have a strong preference about that.
I will revise some of the icons based on a common template.

**Comment by hadjimy** [comment]
See #52

**Comment by HexTree** [comment]
Contact icons look very nice now. Residential life is the same as student life forum, we should really have a house for it. Also, the icon for fchelpdesk specifically says "Community Info Centre" in the embedded text. We could solve this by erasing the text altogether, we needn't have small hard-to-read text in the icon anyway.

**Comment by HexTree** [comment]
Ah, my mistake, just realised you added new icons for those two already. I'll change them.

**Comment by hadjimy** [comment]
"Community Info Centre" goes to the Community Information Centre and the purple helpdesk to F&C helpdesk contact. Shall I erase the text from the community icon? (it should be _center_ also if we use US-english)

**Comment by HexTree** [comment]
Yes, I think the icon will look better without the curvy text, seeing as we already have the text in the contact list.
